name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Setup RabbitMQ
      uses: nijel/rabbitmq-action@v1.0.0
    - name: Test
      run: dotnet run ./src/Services/Authorization/ZeroGravity.Services.Authorization.Api
