name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Setup RabbitMQ
      uses: nijel/rabbitmq-action@v1.0.0
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Download tye
      run: dotnet tool install -g Microsoft.Tye --version "0.11.0-alpha.22111.1"
    - name: Setup RabbitMQ
      uses: nijel/rabbitmq-action@v1.0.0
    - name: Run
      run: cd tools/mssql && docker-compose up -d
